name: Build bottles

on:
  pull_request:
    paths:
      - 'Formula/*'

env:
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build-bottles:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - macos-10.15
          - macos-11.0
    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Build bottles
        run: brew test-bot --skip-recursive-dependents 
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: '*.bottle.*'

