name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        include:
          - os: macos-11
          - os: macos-12
          - os: macos-13
#         - os: ubuntu-22.04
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - id: reset
        if: matrix.os == 'macos-11'
        name: Reset homebrew to bigsur
        run: |
          curl -OL https://raw.githubusercontent.com/autobrew/bundler/master/lib/bigsur-reset.sh
          chmod +x bigsur-reset.sh && ./bigsur-reset.sh

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup || true

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae --skip-dependents
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: '*.bottle.*'
