name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        arch: [intel, arm]
        sdk: [11.3, 13.3]
    runs-on: ${{ matrix.arch == 'arm' && 'macos-14' || 'macos-13' }}
    steps:

      - name: Install MacOS SDK
        run: |
          sdk=${{matrix.sdk}}
          cd /Library/Developer/CommandLineTools/SDKs/
          sudo rm -Rf *
          sudo curl -OL https://github.com/joseluisq/macosx-sdks/releases/download/${sdk}/MacOSX${sdk}.sdk.tar.xz
          sudo tar xf MacOSX${sdk}.sdk.tar.xz
          sudo rm -f MacOSX${sdk}.sdk.tar.xz
          sudo ln -sf MacOSX${sdk}.sdk MacOSX.sdk
          ls -l
          sudo xcode-select -s /Library/Developer/CommandLineTools
          echo "MACOSX_DEPLOYMENT_TARGET=${sdk}" >> $GITHUB_ENV
          sudo mkdir -m777 -p /etc/ssl/private /etc/ssl/misc

      - name: Prepare fake MacOS environment
        run: |
          brew remove $(brew list --formula)
          echo "HOMEBREW_FAKE_MACOS=${{matrix.sdk == '11.3' && '11.7.0' || '13.7.0'}}" >> $GITHUB_ENV
          sed -i.bak 's|MACOSX_DEPLOYMENT_TARGET||g' "$(brew --repo)/Library/Homebrew/build_environment.rb"
          sed -i.bak 's|MACOSX_DEPLOYMENT_TARGET||g' "$(brew --repo)/Library/Homebrew/extend/ENV/shared.rb"

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.arch }}-${{ matrix.sdk }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.arch }}-${{ matrix.sdk }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup || true

      - run: brew test-bot --only-tap-syntax || true
        if: matrix.sdk == '13.3'

      - run: brew test-bot --only-formulae --skip-dependents
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.arch }}_${{ matrix.sdk }}
          path: '*.bottle.*'
